/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Massallys
 */
public class seriesV extends javax.swing.JFrame {

    /**
     * Creates new form moviesV
     */
    public seriesV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPprincipal = new javax.swing.JPanel();
        jLnomeprincipal = new javax.swing.JLabel();
        jLnomeSerie = new javax.swing.JLabel();
        jLmarcador = new javax.swing.JLabel();
        jLserie3 = new javax.swing.JLabel();
        jLserie1 = new javax.swing.JLabel();
        jLserie2 = new javax.swing.JLabel();
        jLserie5 = new javax.swing.JLabel();
        jLserie4 = new javax.swing.JLabel();
        jCassistido1 = new javax.swing.JCheckBox();
        jCassistido2 = new javax.swing.JCheckBox();
        jCassistido3 = new javax.swing.JCheckBox();
        jCassistido4 = new javax.swing.JCheckBox();
        jCassistido5 = new javax.swing.JCheckBox();
        jCassistindo1 = new javax.swing.JCheckBox();
        jCassistindo2 = new javax.swing.JCheckBox();
        jCassistindo3 = new javax.swing.JCheckBox();
        jCassistindo4 = new javax.swing.JCheckBox();
        jCassistindo5 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLnomeprincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLnomeprincipal.setText("Series List");

        jLnomeSerie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLnomeSerie.setText("Nome da Serie:");

        jLmarcador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLmarcador.setText("Marcador:");

        jLserie3.setText("Serie");

        jLserie1.setText("Serie");

        jLserie2.setText("Serie");

        jLserie5.setText("Serie");

        jLserie4.setText("Serie");

        jCassistido1.setText("Assistido");

        jCassistido2.setText("Assistido");

        jCassistido3.setText("Assistido");

        jCassistido4.setText("Assistido");

        jCassistido5.setText("Assistido");

        jCassistindo1.setText("Assistindo");
        jCassistindo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCassistindo1ActionPerformed(evt);
            }
        });

        jCassistindo2.setText("Assistindo");
        jCassistindo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCassistindo2ActionPerformed(evt);
            }
        });

        jCassistindo3.setText("Assistindo");

        jCassistindo4.setText("Assistindo");

        jCassistindo5.setText("Assistindo");

        javax.swing.GroupLayout jPprincipalLayout = new javax.swing.GroupLayout(jPprincipal);
        jPprincipal.setLayout(jPprincipalLayout);
        jPprincipalLayout.setHorizontalGroup(
            jPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPprincipalLayout.createSequentialGroup()
                .addGroup(jPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPprincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLnomeSerie))
                    .addGroup(jPprincipalLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLnomeprincipal))
                    .addGroup(jPprincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLserie5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPprincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLserie3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLserie1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLserie2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLserie4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPprincipalLayout.createSequentialGroup()
                        .addComponent(jLmarcador)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPprincipalLayout.createSequentialGroup()
                        .addComponent(jCassistindo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCassistido1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPprincipalLayout.createSequentialGroup()
                        .addComponent(jCassistindo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCassistido2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPprincipalLayout.createSequentialGroup()
                        .addComponent(jCassistindo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCassistido3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPprincipalLayout.createSequentialGroup()
                        .addComponent(jCassistindo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCassistido4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPprincipalLayout.createSequentialGroup()
                        .addComponent(jCassistindo5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCassistido5)
                        .addContainerGap())))
        );
        jPprincipalLayout.setVerticalGroup(
            jPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPprincipalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLnomeprincipal)
                .addGap(18, 18, 18)
                .addGroup(jPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnomeSerie)
                    .addComponent(jLmarcador))
                .addGap(14, 14, 14)
                .addGroup(jPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLserie1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCassistido1)
                    .addComponent(jCassistindo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLserie2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCassistido2)
                    .addComponent(jCassistindo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLserie3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCassistido3)
                    .addComponent(jCassistindo3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLserie4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCassistido4)
                    .addComponent(jCassistindo4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLserie5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCassistido5)
                    .addComponent(jCassistindo5))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCassistindo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCassistindo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCassistindo1ActionPerformed

    private void jCassistindo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCassistindo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCassistindo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seriesV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seriesV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seriesV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seriesV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seriesV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCassistido1;
    private javax.swing.JCheckBox jCassistido2;
    private javax.swing.JCheckBox jCassistido3;
    private javax.swing.JCheckBox jCassistido4;
    private javax.swing.JCheckBox jCassistido5;
    private javax.swing.JCheckBox jCassistindo1;
    private javax.swing.JCheckBox jCassistindo2;
    private javax.swing.JCheckBox jCassistindo3;
    private javax.swing.JCheckBox jCassistindo4;
    private javax.swing.JCheckBox jCassistindo5;
    private javax.swing.JLabel jLmarcador;
    private javax.swing.JLabel jLnomeSerie;
    private javax.swing.JLabel jLnomeprincipal;
    private javax.swing.JLabel jLserie1;
    private javax.swing.JLabel jLserie2;
    private javax.swing.JLabel jLserie3;
    private javax.swing.JLabel jLserie4;
    private javax.swing.JLabel jLserie5;
    private javax.swing.JPanel jPprincipal;
    // End of variables declaration//GEN-END:variables
}
